#ifndef TORQUELIB_ADDRESSES_OSX_H
#define TORQUELIB_ADDRESSES_OSX_H

// Functions
#define TGEADDR_SIMOBJECT_GETIDSTRING 0x27370
#define TGEADDR_SIMOBJECT_SETHIDDEN 0x29C00
#define TGEADDR_CONTAINER_CASTRAY 0x192B80
#define TGEADDR_FILESTREAM_OPEN 0x505C0
#define TGEADDR_FILE_OPEN 0x1EA350
#define TGEADDR_FILE_GETPOSITION 0x1E8D30
#define TGEADDR_FILE_SETPOSITION 0x1E9D70
#define TGEADDR_FILE_GETSIZE 0x1E94B0
#define TGEADDR_FILE_FLUSH 0x1E9F30
#define TGEADDR_FILE_CLOSE 0x1E9FA0
#define TGEADDR_FILE_GETSTATUS 0x1E8D60
#define TGEADDR_FILE_READ 0x1EA030
#define TGEADDR_FILE_WRITE 0x1EA0F0
#define TGEADDR_FILE_DTOR 0x1E9C50
#define TGEADDR_FILE_SETSTATUS_1 0x1E8DB0
#define TGEADDR_PATHEDINTERIOR_ADVANCE 0x24B8B0
#define TGEADDR_PATHEDINTERIOR_COMPUTENEXTPATHSTEP 0x24C6C0
#define TGEADDR__STRINGTABLE_INSERT 0x4AFF0
#define TGEADDR_CON_INIT 0x3C380
#define TGEADDR_CON_PRINTF 0x3B5A0
#define TGEADDR_CON__PRINTF 0x3AC20
#define TGEADDR_CON_WARNF_1V 0x3B2A0
#define TGEADDR_CON_WARNF_2V 0x3B2F0
#define TGEADDR_CON_ERRORF_1V 0x3B130
#define TGEADDR_CON_ERRORF_2V 0x3B2C0
#define TGEADDR_CON_ADDCOMMAND_5_STRING 0x3A130
#define TGEADDR_CON_ADDCOMMAND_5_VOID 0x3A190
#define TGEADDR_CON_ADDCOMMAND_5_INT 0x3A250
#define TGEADDR_CON_ADDCOMMAND_5_FLOAT 0x3A2B0
#define TGEADDR_CON_ADDCOMMAND_5_BOOL 0x3A1F0
#define TGEADDR_CON_ADDCOMMAND_6_STRING 0x3C5E0
#define TGEADDR_CON_ADDCOMMAND_6_VOID 0x3C6A0
#define TGEADDR_CON_ADDCOMMAND_6_INT 0x3C760
#define TGEADDR_CON_ADDCOMMAND_6_FLOAT 0x3C820
#define TGEADDR_CON_ADDCOMMAND_6_BOOL 0x3C8E0
#define TGEADDR_CON_SETVARIABLE 0x3B9A0
#define TGEADDR_CON_SETLOCALVARIABLE 0x3B5C0
#define TGEADDR_CON_SETBOOLVARIABLE 0x3BDA0
#define TGEADDR_CON_SETINTVARIABLE 0x3BE30
#define TGEADDR_CON_SETFLOATVARIABLE 0x3BED0
#define TGEADDR_CON_EXECUTE 0x3B4A0
#define TGEADDR_CON_EVALUATE 0x3BBF0
#define TGEADDR_CON_EVALUATEF 0x3A310
#define TGEADDR_CON_GETRETURNBUFFER 0x444E0
#define TGEADDR_CON_EXPANDSCRIPTFILENAME 0x3B150
#define TGEADDR_PLATFORM_DUMPPATH 0x1E9390
#define TGEADDR_PLATFORM_GETWORKINGDIRECTORY 0x1E8E10
#define TGEADDR_PLATFORM_ISSUBDIRECTORY 0x1E8EE0
#define TGEADDR_PLATFORM_GETFILETIMES 0x1E97E0
#define TGEADDR_NAMESPACE_INIT 0x348D0
#define TGEADDR_PARTICLEENGINE_INIT 0xCC510
#define TGEADDR_SIM_FINDOBJECT 0x257D0
#define TGEADDR_NET_INIT 0x1F0340
#define TGEADDR_MARBLE_DOPOWERUP 0x2576B0
#define TGEADDR_MARBLE_ADVANCEPHYSICS 0x25B990
#define TGEADDR_ABSTRACTCLASSREP_INITIALIZE 0x31FF0
#define TGEADDR_CLIENTPROCESS 0xEBA60
#define TGEADDR_DSPRINTF 0x1EDBC0
#define TGEADDR_DVSPRINTF 0x1EDBF0
#define TGEADDR_DFREE 0x17C360
#define TGEADDR_DQSORT 0x1EDC80
#define TGEADDR_VECTORRESIZE 0x497C0
#define TGEADDR_CAMERA_ADVANCEPHYSICS 0xFB210
#define TGEADDR_RESMANAGER_OPENSTREAM_STR 0x4E0D0
#define TGEADDR_RESMANAGER_OPENSTREAM_RESOURCEOBJECT 0x4DD50
#define TGEADDR_RESMANAGER_CLOSESTREAM 0x4B910
#define TGEADDR_RESMANAGER_FIND 0x4C890
#define TGEADDR_RESMANAGER_GETSIZE 0x4CDD0
#define TGEADDR_RESMANAGER_GETCRC 0x4E3A0
#define TGEADDR_RESMANAGER_SEARCHPATH 0x4D8F0
#define TGEADDR_RESMANAGER_SETMODZIP 0x4BFD0
#define TGEADDR_NET_BIND 0x1F0BB0
#define TGEADDR_TIMEMANAGER_PROCESS 0x1EBB20
#define TGEADDR_GAMEBASE_PACKUPDATE 0xE83A0
#define TGEADDR_GAMEBASE_UNPACKUPDATE 0xE8B20
#define TGEADDR_INTERIORINSTANCE_PACKUPDATE 0x151740
#define TGEADDR_INTERIORINSTANCE_UNPACKUPDATE 0x151DF0
#define TGEADDR_TSSTATIC_PACKUPDATE 0xFF020
#define TGEADDR_TSSTATIC_UNPACKUPDATE 0xFEF20
#define TGEADDR_BITSTREAM_WRITEINT 0x549F0
#define TGEADDR_BITSTREAM_READINT 0x53A40

// Class fields
#define TGEOFF_CONSOLEOBJECT_VTABLE 0
#define TGEOFF_SIMOBJECT_ID 0x20
#define TGEOFF_SCENEOBJECT_TRANSFORM 0x9C
#define TGEOFF_SCENEOBJECT_WORLDBOX 0x140
#define TGEOFF_GAMEBASE_CONTROLLINGCLIENT 0x270
#define TGEOFF_FILE_HANDLE 0x4
#define TGEOFF_FILE_CAPABILITIES 0xC
#define TGEOFF_ABSTRACTCLASSREP_CLASSNAME 0x2C
#define TGEOFF_STREAM_VTABLE 0x0
#define TGEOFF_STREAM_STATUS 0x4
#define TGEOFF_GAMEINTERFACE_VTABLE 0x0

// Globals
#define TGEADDR_MSERVERCONNECTION 0x310B5C
#define TGEADDR_GCLIENTCONTAINER 0x310560
#define TGEADDR_GSERVERCONTAINER 0x3105C0
#define TGEADDR_STRINGTABLE 0x2DA55C
#define TGEADDR_RESOURCEMANAGER 0x2DA560
#define TGEADDR_GAME 0x2DB7E8

// Virtual functions
enum
{
	TGEVIRT_STREAM_DTOR,
	TGEVIRT_STREAM__READ = 2,
	TGEVIRT_STREAM__WRITE,
	TGEVIRT_STREAM_HASCAPABILITY,
	TGEVIRT_STREAM_GETPOSITION,
	TGEVIRT_STREAM_SETPOSITION,
	TGEVIRT_STREAM_GETSTREAMSIZE,
	TGEVIRT_STREAM_READSTRING,
	TGEVIRT_STREAM_WRITESTRING
};
enum
{
	TGEVIRT_CONSOLEOBJECT_DESTRUCTOR = 1,
	TGEVIRT_NETOBJECT_PACKUPDATE = 22,
	TGEVIRT_NETOBJECT_UNPACKUPDATE,
	TGEVIRT_SCENEOBJECT_DISABLECOLLISION = 25,
	TGEVIRT_SCENEOBJECT_ENABLECOLLISION,
	TGEVIRT_SCENEOBJECT_ISDISPLACABLE,
	TGEVIRT_SCENEOBJECT_GETMOMENTUM,
	TGEVIRT_SCENEOBJECT_SETMOMENTUM,
	TGEVIRT_SCENEOBJECT_GETMASS,
	TGEVIRT_SCENEOBJECT_DISPLACEOBJECT,
	TGEVIRT_SCENEOBJECT_SETTRANSFORM,
	TGEVIRT_SHAPEBASE_GETCAMERATRANSFORM = 85
};
enum
{
	TGEVIRT_GAMEINTERFACE_POSTEVENT = 4
};

#endif // TORQUELIB_ADDRESSES_OSX_H
